nodeLinker: node-modules

npmMinimalAgeGate: 2880
npmPreapprovedPackages:
  - '@navikt/aap-felles-prettier'
  - '@navikt/aap-felles-utils'
  - '@navikt/eslint-config-aap'

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_AUTH_TOKEN:-}'
    npmRegistryServer: 'https://npm.pkg.github.com'
