apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: meldekort-alerts
  namespace: aap
  labels:
    team: aap
    app: meldekort
spec:
  groups:
    - name: 'aap-meldekort-alerts'
      rules:
        - alert: AAP Meldekort - app nede
          expr: kube_deployment_status_replicas_unavailable{deployment="meldekort",job="kubernetes-service-endpoints"} > 0
          for: 10m
          annotations:
            summary: 'aap-meldekort har utilgjengelige podder i prod'
            action: 'kubectl describe pod -l app=meldekort -n aap` for events og `kubectl get pods -l app=meldekort -n aap` for å se feilende podder'
          labels:
            namespace: aap
            severity: danger
        - alert: AAP meldekort -kontinuerlig restart
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"meldekort"}[5m])) by (container) > 2
          for: 2m
          annotations:
            summary: 'AAP meldekort har restartet flere ganger de siste 5 minuttene'
            action: 'Se `kubectl describe pod meldekort` for events, og `kubectl logs meldekort` for logger'
          labels:
            namespace: aap
            severity: danger
        - alert: AAP meldekort - høy feilrate i logger
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="meldekort",log_level=~"Error"}[10m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="meldekort"}[10m]))) > 15
          for: 5m
          annotations:
            summary: 'Høy feilrate i prod logger'
            action: '<https://logs.adeo.no/goto/c5feac60-58ff-11ed-b3e8-d969437dd878|Check logs>'
          labels:
            namespace: aap
            severity: danger
