/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/ansvarlig-system': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': 'AAP' | 'FELLES';
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/debug/saker': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['kotlin.Any'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/skjema/{meldekortId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description meldekortId */
          meldekortId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.meldekort.MeldekortResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/skjema/{meldekortId}/neste-steg': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description meldekortId */
          meldekortId: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.meldekort.MeldekortRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.meldekort.MeldekortResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/skjema/{meldekortId}/lagre': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description meldekortId */
          meldekortId: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.meldekort.MeldekortRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.meldekort.MeldekortResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/meldekort/neste': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.meldekort.KommendeMeldekortDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/meldekort/historisk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.meldekort.HistoriskMeldekortDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/meldekort/historisk/meldeperiode': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.meldekort.PeriodeDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.meldekort.HistoriskMeldekortDetaljerDto'][];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/meldekort/{meldekortId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description meldekortId */
          meldekortId: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.meldekort.MeldekortKorrigeringRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/test/proxy/meldegrupper': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['kotlin.Any'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/test/proxy/meldekort': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['kotlin.Any'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/test/proxy/historiskemeldekort': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['kotlin.Any'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/test/proxy/meldekortdetaljer/{meldekortId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description meldekortId */
          meldekortId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['kotlin.Any'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/arena/test/proxy/korrigerte-meldekort/{meldekortId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description meldekortId */
          meldekortId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['kotlin.Any'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bruker-info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.meldekort.InfoDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/utfylling/tilstand': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.meldekort.FlytTilstandDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/utfylling/lagre-neste': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.meldekort.NyFlytTilstandDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.meldekort.FlytTilstandResponseDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/utfylling/lagre': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.meldekort.NyFlytTilstandDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.meldekort.FlytTilstandResponseDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/feilende': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.api.JobbInfoDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/planlagte-jobber': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.api.JobbInfoDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/rekjor/{jobbId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/avbryt/{jobbId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/rekjorAlleFeilede': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/sisteKj\u00F8rte': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.api.JobbInfoDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    'kotlin.Any': Record<string, never>;
    'no.nav.aap.arena.ArenaInnsendingFeiletException.InnsendingFeil': {
      kode: string;
      params?: string[] | null;
    };
    'no.nav.aap.meldekort.DagerInfoDto': {
      /**
       * Format: date
       * @example 2025-02-17
       */
      dato: string;
      'harV\u00E6rtP\u00E5Ferie'?: boolean | null;
      'harV\u00E6rtP\u00E5tiltakKursEllerUtdanning'?: boolean | null;
      'harV\u00E6rtSyk'?: boolean | null;
      /** Format: double */
      timerArbeidet?: number | null;
    };
    'no.nav.aap.meldekort.Feil': components['schemas']['no.nav.aap.meldekort.InnsendingFeil'];
    'no.nav.aap.meldekort.FlytTilstandDto': {
      meldeperiode: components['schemas']['no.nav.aap.meldekort.MeldeperiodeDto'];
      skjema: components['schemas']['no.nav.aap.meldekort.SkjemaDto'];
      /** @enum {string} */
      steg: 'INTRODUKSJON' | 'SPØRSMÅL' | 'UTFYLLING' | 'BEKREFT' | 'KVITTERING';
    };
    'no.nav.aap.meldekort.FlytTilstandResponseDto':
      | components['schemas']['no.nav.aap.meldekort.FlytTilstandResponseDto.Feil']
      | components['schemas']['no.nav.aap.meldekort.FlytTilstandResponseDto.Ok'];
    'no.nav.aap.meldekort.FlytTilstandResponseDto.Feil': Record<string, never>;
    'no.nav.aap.meldekort.FlytTilstandResponseDto.Ok': {
      flytTilstand: components['schemas']['no.nav.aap.meldekort.FlytTilstandDto'];
    };
    'no.nav.aap.meldekort.HistoriskMeldekortDetaljerDto': {
      /** Format: double */
      'bruttoBel\u00F8p'?: number | null;
      dager?: components['schemas']['no.nav.aap.meldekort.DagerInfoDto'][] | null;
      'harDuGjennomf\u00F8rtAvtaltAktivitetKursEllerUtdanning': boolean;
      harDuHattFerie: boolean;
      harDuJobbet: boolean;
      'harDuV\u00E6rtSyk': boolean;
      /**
       * Format: date
       * @example 2025-02-17
       */
      innsendtDato?: string | null;
      kanEndres: boolean;
      /** Format: int64 */
      meldekortId: number;
      meldeperiode: components['schemas']['no.nav.aap.meldekort.PeriodeDto'];
      /** @enum {string} */
      status: 'OVERSTYRT_AV_ANNET_MELDEKORT' | 'INNSENDT' | 'FERDIG' | 'FEILET';
      /** @enum {string} */
      type: 'VANLIG' | 'ETTERREGISTRERING' | 'KORRIGERING' | 'UKJENT';
    };
    'no.nav.aap.meldekort.HistoriskMeldekortDto': {
      meldeperiode: components['schemas']['no.nav.aap.meldekort.PeriodeDto'];
      /** @enum {string} */
      status: 'OVERSTYRT_AV_ANNET_MELDEKORT' | 'INNSENDT' | 'FERDIG' | 'FEILET';
    };
    'no.nav.aap.meldekort.InfoDto': {
      forrigeMeldeperiode?: components['schemas']['no.nav.aap.meldekort.MeldeperiodeDto'];
      nesteMeldeperiode?: components['schemas']['no.nav.aap.meldekort.MeldeperiodeDto'];
      'n\u00E5v\u00E6rendeMeldeperiode'?: components['schemas']['no.nav.aap.meldekort.MeldeperiodeDto'];
    };
    'no.nav.aap.meldekort.InnsendingFeil': {
      innsendingFeil: components['schemas']['no.nav.aap.arena.ArenaInnsendingFeiletException.InnsendingFeil'][];
    };
    'no.nav.aap.meldekort.KommendeMeldekortDto': {
      /** Format: int32 */
      antallUbesvarteMeldekort: number;
      nesteMeldekort?: components['schemas']['no.nav.aap.meldekort.NesteMeldekortDto'];
    };
    'no.nav.aap.meldekort.MeldekortKorrigeringRequest': {
      dager: components['schemas']['no.nav.aap.meldekort.DagerInfoDto'][];
      'harDuGjennomf\u00F8rtAvtaltAktivitetKursEllerUtdanning': boolean;
      harDuHattFerie: boolean;
      harDuJobbet: boolean;
      'harDuV\u00E6rtSyk': boolean;
    };
    'no.nav.aap.meldekort.MeldekortRequest': {
      meldekort: components['schemas']['no.nav.aap.meldekort.MeldekortSkjemaDto'];
      /** @enum {string} */
      'n\u00E5v\u00E6rendeSteg':
        | 'INTRODUKSJON'
        | 'SPØRSMÅL'
        | 'UTFYLLING'
        | 'STEMMER_OPPLYSNINGENE'
        | 'INNSENDING_VANLIG_MELDEKKORT'
        | 'KVITTERING';
    };
    'no.nav.aap.meldekort.MeldekortResponse': {
      feil?: components['schemas']['no.nav.aap.meldekort.Feil'];
      meldekort: components['schemas']['no.nav.aap.meldekort.MeldekortSkjemaDto'];
      periode: components['schemas']['no.nav.aap.meldekort.PeriodeDto'];
      /** @enum {string} */
      steg:
        | 'INTRODUKSJON'
        | 'SPØRSMÅL'
        | 'UTFYLLING'
        | 'STEMMER_OPPLYSNINGENE'
        | 'INNSENDING_VANLIG_MELDEKKORT'
        | 'KVITTERING';
      /**
       * Format: date
       * @example 2025-02-17
       */
      tidligsteInnsendingsDato: string;
    };
    'no.nav.aap.meldekort.MeldekortSkjemaDto': {
      dager: components['schemas']['no.nav.aap.meldekort.DagerInfoDto'][];
      'harDuGjennomf\u00F8rtAvtaltAktivitetKursEllerUtdanning'?: boolean | null;
      harDuHattFerie?: boolean | null;
      harDuJobbet?: boolean | null;
      'harDuV\u00E6rtSyk'?: boolean | null;
      stemmerOpplysningene?: boolean | null;
      svarerDuSant?: boolean | null;
    };
    'no.nav.aap.meldekort.MeldeperiodeDto': {
      /**
       * Format: date
       * @example 2025-02-17
       */
      fastsattDag: string;
      innsendingsvindu: components['schemas']['no.nav.aap.meldekort.PeriodeDto'];
      meldeperiode: components['schemas']['no.nav.aap.meldekort.PeriodeDto'];
    };
    'no.nav.aap.meldekort.NesteMeldekortDto': {
      kanSendesInn: boolean;
      /** Format: int64 */
      meldekortId: number;
      meldeperiode: components['schemas']['no.nav.aap.meldekort.PeriodeDto'];
      /**
       * Format: date
       * @example 2025-02-17
       */
      tidligsteInnsendingsDato: string;
    };
    'no.nav.aap.meldekort.NyFlytTilstandDto': {
      skjema: components['schemas']['no.nav.aap.meldekort.SkjemaDto'];
      /** @enum {string} */
      steg: 'INTRODUKSJON' | 'SPØRSMÅL' | 'UTFYLLING' | 'BEKREFT' | 'KVITTERING';
    };
    'no.nav.aap.meldekort.PeriodeDto': {
      /**
       * Format: date
       * @example 2025-02-17
       */
      fom: string;
      /**
       * Format: date
       * @example 2025-02-17
       */
      tom: string;
    };
    'no.nav.aap.meldekort.SkjemaDto': {
      dager: components['schemas']['no.nav.aap.meldekort.SkjemadagDto'][];
      harDuJobbet?: boolean | null;
    };
    'no.nav.aap.meldekort.SkjemadagDto': {
      /**
       * Format: date
       * @example 2025-02-17
       */
      dato: string;
      /** Format: double */
      timerArbeidet?: number | null;
    };
    'no.nav.aap.motor.api.JobbInfoDto': {
      /** Format: int32 */
      'antallFeilendeFors\u00F8k': number;
      beskrivelse: string;
      feilmelding?: string | null;
      /** Format: int64 */
      id: number;
      /** @description Key type: kotlin.String */
      metadata: {
        [key: string]: string;
      };
      navn: string;
      /**
       * Format: date-time
       * @example 2025-02-17T10:31:39.594565
       */
      'planlagtKj\u00F8retidspunkt': string;
      /** @enum {string} */
      status: 'KLAR' | 'PLUKKET' | 'FERDIG' | 'FEILET' | 'AVBRUTT';
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
